### ISSUE TITLE
Could we consider migrating to mdbook?

### ISSUE THREAD

**Issue by JohnTitor** [sgrif/diesel.rs-website#118]
The website is built with middleman but its version is too old and we don't familiar with it. That makes it difficult to maintain (e.g. #106). Could we consider migrating to mdbook (or something else, which is easy to maintain) to make it easier?
cc @weiznich

**Comment by weiznich** [comment]
I would be fine with migrating this to some other platform like `mdbook` (or `pandoc`), as I'm not familiar with middleman or any other ruby based system as well. Having just markdown files + maybe some html/css for styling would be great.
That written, at least I do not have the capacity to work on the migration myself. So if anyone is interested in tackling this problem feel free go for it. A bonus point would be that we keep the general structure of the old web page so that old links continue to work.

**Comment by weiznich** [comment]
Closed by #122
