### ISSUE TITLE
returning_clauses_for_sqlite_3_35 flag not working

### ISSUE THREAD

**Issue by Meliodus** [sgrif/diesel.rs-website#194]
it seems like with sqlite diesel traits its not queryable but execute work fine with my `conn`.
<img width="1244" alt="Screenshot 2023-04-26 at 7 32 40 PM" src="https://user-images.githubusercontent.com/3616579/234600233-b3bd1e8a-8a89-430f-9b61-3e7886438e1f.png">

```
 let now = Utc::now().to_string();
            let ne = NewEmployee {
                name: &meta["Employee First Name and Last Name"].to_string().replace("\"", ""),
                department: &"",
                software_ids: &"",
                created_on: &now,
                created_by:  & "ab-system",
                updated_on: &now,
                updated_by:  & "ab-system",
            };


         diesel::insert_into(employee::table)
                .values(ne)
                .execute(conn)
                .expect("Error saving new requestor");
        
         // Get the ID of the last inserted row
         let result = employee::dsl::employee.filter(updated_on.eq(now))
         .get_result::<Employee>(conn).unwrap()   <<<==== Here conn showing the above error
     

println!("{:#?}", result);
```

the traits are in order while insert_into.

**Comment by weiznich** [comment]
This issue tracker is for bugs or other issues with diesels web page. It's not the right place to ask for support for issues with your diesel code. Also you did post the same question already to the diesel repository. It's highly discouraged to post the same question again, just because the answer did not satisfy you. I suggest that you spend the time to update your original question with more details, for example with a complete minimal reproducible example. Only then it's possible to help you with more details.
